project:
  name: "prx11"
  version: "1"

settings:
  max_configs: 2000
  timeout: 20
  max_workers: 50

subscription_files:
  hiddify: "prx11-hiddify.txt"
  insta: "prx11-insta-youto.txt"
  vmess: "prx11-vmess.txt"
  vless: "prx11-vless.txt"
  ss: "prx11-ss.txt"
  trojan: "prx11-trojan.txt"
